title: Emi's portfolio 
name: null 
logo: https://media.licdn.com/dms/image/v2/D5603AQHbmEKB5EP3MQ/profile-displayphoto-shrink_800_800/B56ZSux.8lGoAg-/0/1738099126693?e=1764201600&v=beta&t=lBHDT7CqJq-ZMoQ-KS1xNIk5mMtgLXaRdhpcjPRLnxk
remote_theme: pages-themes/architect@v0.2.0 
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
