title: Emi's portfolio 
name: null 
logo: https://blogs.tropicalstudies.org/field-notes/wp-content/uploads/sites/7/2023/07/ESM-TB23-Stone-Bridge-300x399.jpg 
remote_theme: pages-themes/time-machine@v0.2.0
plugins: -jekyll-remote-theme # add this line to the plugins list if you already have one
